use amazon_db;
-- 1 . Objective One
/* 1 Query the top 10 products by total sales value, including product name,
total quantity sold, and total sales value. */

select p.product_name, 
	sum(o.quantity) as total_quantity_sold ,
    sum(o.quantity*o.price_per_unit) as total_sales_value
from orders_items o
join products p 
on  p.product_id = o.product_id
group by p.product_name
order by total_sales_value desc;

/*2. Calculate total revenue generated by each product category and include 
the percentage contribution of each category to total revenue.  */

select 
	c.category_name, 
    sum(o.quantity*o.price_per_unit) as category_revenue,
   ROUND(
        SUM(o.quantity * o.price_per_unit) * 100
        / SUM(SUM(o.quantity * o.price_per_unit)) OVER (),
        2
    ) AS percentage_contribution
from orders_items o
join products p 
	on o.product_id = p.product_id
join category c
	on c.category_id = p.category_id
group by c.category_name
;

/*3. Compute the Average Order Value (AOV) for each customer and include
 only customers with more than 5 orders.  */
 
SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.quantity * oi.price_per_unit) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM customers c
JOIN orders o 
	ON c.customer_id = o.customer_id
JOIN orders_items oi 
	ON o.order_id = oi.order_id
GROUP BY 
	c.customer_id, 
    c.first_name, 
    c.last_name
HAVING COUNT(DISTINCT o.order_id) > 5
ORDER BY avg_order_value DESC;
 
/*4. Monthly total sales over the past year, showing 
current month sales and previous month sales  */

SELECT  
    year,
    month,
    total_sale AS current_month_sale,
    LAG(total_sale, 1) OVER (ORDER BY year, month) AS last_month_sale
FROM (
    SELECT  
        EXTRACT(MONTH FROM o.order_date) AS month,
        EXTRACT(YEAR FROM o.order_date) AS year,
        ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS total_sale
    FROM orders AS o
    JOIN orders_items AS oi 
        ON oi.order_id = o.order_id
    WHERE o.order_date >= CURDATE() - INTERVAL 1 YEAR
    GROUP BY year, month
    ORDER BY year, month
) AS t1;


/*5. Customers who registered but never placed an order, 
with time since registration  */

SELECT 
	c.customer_id,
	CONCAT(c.first_name, ' ', c.last_name) AS full_name,
	c.state
FROM customers AS c
LEFT JOIN
orders AS o
ON o.customer_id = c.customer_id
WHERE o.customer_id IS NULL;

/*6. Identify the least-selling product category for each state and include the total
 sales for that category within each state. */
 
WITH ranking_table AS (
    SELECT 
        c.state,
        cat.category_name,
        SUM(oi.quantity * oi.price_per_unit) AS total_sales,
        ROW_NUMBER() OVER (
            PARTITION BY c.state
            ORDER BY SUM(oi.quantity * oi.price_per_unit) ASC
        ) AS rn
    FROM orders o
    JOIN customers c 
        ON o.customer_id = c.customer_id
    JOIN orders_items oi 
        ON o.order_id = oi.order_id
    JOIN products p 
        ON oi.product_id = p.product_id
    JOIN category cat 
        ON cat.category_id = p.category_id
    GROUP BY 
        c.state, 
        cat.category_name
)
SELECT 
    state,
    category_name,
    total_sales
FROM ranking_table
WHERE rn = 1
ORDER BY state;

/*7. Identify the least-selling product category for each state and include the total
 sales for that category within each state. */
 
 SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS full_name,
    ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS cltv,
    RANK() OVER (
        ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC
    ) AS cltv_rank
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    full_name
ORDER BY cltv DESC;

/*8. Query products with stock levels below a certain threshold (e.g., less
 than 10 units) and include the last restock date and warehouse information. */
 
 SELECT
    p.product_id,
    p.product_name,
    i.stock AS current_stock,
    i.last_stock_date AS last_restock_date,
    i.warehouse_iseller_idd
FROM inventory i
JOIN products p
    ON i.product_id = p.product_id
WHERE i.stock < 10
ORDER BY i.stock ASC;


/*9. Query products with stock levels below a certain threshold (e.g., less
 than 10 units) and include the last restock date and warehouse information. */

SELECT
    payment_status,
    COUNT(*) AS total_payments,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),
        2
    ) AS percentage_of_total
FROM payments
GROUP BY payment_status
ORDER BY total_payments DESC;


 
 
/*10. Top 10 products by number of returns and return rate (% of total units sold) */
SELECT
    p.product_id,
    p.product_name,
    SUM(
        CASE 
            WHEN s.return_date IS NOT NULL THEN oi.quantity 
            ELSE 0 
        END
    ) AS returned_units,
    SUM(oi.quantity) AS total_units_sold,
    ROUND(
        SUM(
            CASE 
                WHEN s.return_date IS NOT NULL THEN oi.quantity 
                ELSE 0 
            END
        ) * 100.0 / SUM(oi.quantity),
        2
    ) AS return_rate_percentage
FROM orders_items oi
JOIN orders o
    ON oi.order_id = o.order_id
JOIN shipping s
    ON o.order_id = s.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
HAVING SUM(
        CASE 
            WHEN s.return_date IS NOT NULL THEN oi.quantity 
            ELSE 0 
        END
    ) > 0
ORDER BY returned_units DESC
LIMIT 10;
